### ISSUE TITLE
Problème for using G19 on arch

### ISSUE THREAD

**Issue by Cyberdr3am** [GRayHook/ambient-light#1]
Hi,

I have try to use you Logintech G19 Linux Daemon but when i start it i have got a lot of error and the keyboard don't change.
For ambiant-light i try to install it with make but i have some error during the build of the program.

Can you ask me how i can use your Logintech G19 Linux Daemon and ambient-light ?
I already install Pyusb, Pillow, Pynput.

Thx for your work

**Comment by GRayHook** [comment]
Hi! Can you attach all of this errors as a text file?

But first, let me guess. Is the error during build "X11/Xlib.h: No such file or directory"? You should install `libx11-dev` to solve it. Also, `make install` places the executable file to `/usr/local/bin`, that are not writable by regular user: use `sudo make install`. And G19 Linux Daemon needs to be installed too, by `python3 ./setup.py install`. It has a C-code that have to be compiled. You may need a `python3-dev` to compile it.

I have to write a sufficient instructions and to test requirements... :crying_cat_face:

**Comment by Cyberdr3am** [comment]
Thx for the help.

For the deamon i must use sudo to install it. After launch g19d i have got this error

Exception in thread AppMgr thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/g19d-0.9.0-py3.8-linux-x86_64.egg/g19d/__main__.py", line 28, in routine
    CONTEXT["APPMGR"] = AppMgr()
  File "/usr/lib/python3.8/site-packages/g19d-0.9.0-py3.8-linux-x86_64.egg/g19d/appmgr/__init__.py", line 26, in __init__
    logging.basicConfig(format=fmat, filename=fname, level=logging.DEBUG)
  File "/usr/lib/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/g19d/masterdream.log'

For Ambient-light with make

mkdir build -p
mkdir build/transports -p
gcc -Isrc src/transports/*.c src/ambient_light.c -lX11 -o build/ambient_light -g
/usr/bin/ld?: /tmp/ccyeNXo7.o:/home/masterdream/ambient-light/src/transports/logitech_lcd.h:5?: d?finitions multiples de ??logitech_lcd??; /tmp/ccb6MuN7.o:/home/masterdream/ambient-light/src/transports/logitech_lcd.h:5?: d?fini pour la premi?re fois ici
/usr/bin/ld?: /tmp/ccyeNXo7.o:/home/masterdream/ambient-light/src/transports/g13.h:5?: d?finitions multiples de ??g13??; /tmp/cc5UQYp8.o:/home/masterdream/ambient-light/src/transports/g13.h:5?: d?fini pour la premi?re fois ici
collect2: erreur: ld a retourn? le statut de sortie 1
make: *** [Makefile:6 : build/ambient_light] Erreur 1

**Comment by GRayHook** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory: '/var/log/g19d/masterdream.log'`

Daemon needs to have '/var/log/g19d/' directory created to place there logs. 

Give attention that to run daemon by regular user you need rigths to device. It's may be done with udev rules.
<details><summary>/etc/udev/rules.d/90-logitech.rules</summary>
<pre>
SUBSYSTEM=="usb", ATTR{idVendor}=="046d", ATTR{idProduct}=="c229", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="046d", ATTR{idProduct}=="c228", MODE="666"
</pre>
</details>

About ambient-light. Could you try [issue-1 branch](https://github.com/GRayHook/ambient-light/tree/issue-1)?

**Comment by Cyberdr3am** [comment]
I have create the folder /var/log/g19d and it work !
I don't add rules so i use sudo to start it.
( When the screen show the clock i am so happy ! )
For ambient-light the branch issue-1 solve the problem.

Some questions :

I would like to know if it would be possible to display something else on the keyboard screen such as showing system performance for example.
To change the image I think we have to recompile it and change the image available in the g19d folder.
Regarding the leds of the screen I would like to know if I can choose a color as the default color (Ambient-light is really good but during a movie or other it's quite complicated to write with a keyboard that changes colors) .

Another suggestion or bug. If ambient-light is kill the deamon uses 100% of the cpu and I have to restart it to avoid overheating the processor.

**Comment by GRayHook** [comment]
> I would like to know if it would be possible to display something else on the keyboard screen such as showing system performance for example.

It is possible. I will add performance monitor, video player(i hope i'll be able to make youtube player :heart_eyes:), keybinding's layout, control of RGB, etc. But firstly daemon needs to be stabilized. 

> To change the image I think we have to recompile it and change the image available in the g19d folder.

Recompile is unnecessary, replacing `/usr/lib/python3.8/site-packages/g19d-0.9.0-py3.8-linux-x86_64.egg/g19d/background.png`  should be enough.

> Regarding the leds of the screen I would like to know if I can choose a color as the default color

This, previous one and other things i gonna make configurable by some simple GUI utility.

> If ambient-light is kill the deamon uses 100% of the cpu

It's sad. I can't reproduce this behavior yet, but i'll make it configurable soon. It is my next planned feature. Stay tuned.

**Comment by Cyberdr3am** [comment]
Ok thx for your help.
I wait for the update with all this thing.
Have a nice day.
